# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\dev\cmake\bin\cmake.exe

# The command to remove a file.
RM = C:\dev\cmake\bin\cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Source\rpi-os

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Source\rpi-os

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	C:\dev\cmake\bin\cmake-gui.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	C:\dev\cmake\bin\cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Source\rpi-os\CMakeFiles C:\Source\rpi-os\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Source\rpi-os\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rpi-os

# Build rule for target.
rpi-os: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 rpi-os
.PHONY : rpi-os

# fast build rule for target.
rpi-os/fast:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/build
.PHONY : rpi-os/fast

src/asm-functions.obj: src/asm-functions.s.obj

.PHONY : src/asm-functions.obj

# target to build an object file
src/asm-functions.s.obj:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/asm-functions.s.obj
.PHONY : src/asm-functions.s.obj

src/cstubs.obj: src/cstubs.c.obj

.PHONY : src/cstubs.obj

# target to build an object file
src/cstubs.c.obj:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/cstubs.c.obj
.PHONY : src/cstubs.c.obj

src/cstubs.i: src/cstubs.c.i

.PHONY : src/cstubs.i

# target to preprocess a source file
src/cstubs.c.i:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/cstubs.c.i
.PHONY : src/cstubs.c.i

src/cstubs.s: src/cstubs.c.s

.PHONY : src/cstubs.s

# target to generate assembly for a file
src/cstubs.c.s:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/cstubs.c.s
.PHONY : src/cstubs.c.s

src/main.obj: src/main.cpp.obj

.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/rpi-armtimer.obj: src/rpi-armtimer.c.obj

.PHONY : src/rpi-armtimer.obj

# target to build an object file
src/rpi-armtimer.c.obj:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-armtimer.c.obj
.PHONY : src/rpi-armtimer.c.obj

src/rpi-armtimer.i: src/rpi-armtimer.c.i

.PHONY : src/rpi-armtimer.i

# target to preprocess a source file
src/rpi-armtimer.c.i:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-armtimer.c.i
.PHONY : src/rpi-armtimer.c.i

src/rpi-armtimer.s: src/rpi-armtimer.c.s

.PHONY : src/rpi-armtimer.s

# target to generate assembly for a file
src/rpi-armtimer.c.s:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-armtimer.c.s
.PHONY : src/rpi-armtimer.c.s

src/rpi-assert.obj: src/rpi-assert.c.obj

.PHONY : src/rpi-assert.obj

# target to build an object file
src/rpi-assert.c.obj:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-assert.c.obj
.PHONY : src/rpi-assert.c.obj

src/rpi-assert.i: src/rpi-assert.c.i

.PHONY : src/rpi-assert.i

# target to preprocess a source file
src/rpi-assert.c.i:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-assert.c.i
.PHONY : src/rpi-assert.c.i

src/rpi-assert.s: src/rpi-assert.c.s

.PHONY : src/rpi-assert.s

# target to generate assembly for a file
src/rpi-assert.c.s:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-assert.c.s
.PHONY : src/rpi-assert.c.s

src/rpi-event.obj: src/rpi-event.c.obj

.PHONY : src/rpi-event.obj

# target to build an object file
src/rpi-event.c.obj:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-event.c.obj
.PHONY : src/rpi-event.c.obj

src/rpi-event.i: src/rpi-event.c.i

.PHONY : src/rpi-event.i

# target to preprocess a source file
src/rpi-event.c.i:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-event.c.i
.PHONY : src/rpi-event.c.i

src/rpi-event.s: src/rpi-event.c.s

.PHONY : src/rpi-event.s

# target to generate assembly for a file
src/rpi-event.c.s:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-event.c.s
.PHONY : src/rpi-event.c.s

src/rpi-gpio.obj: src/rpi-gpio.c.obj

.PHONY : src/rpi-gpio.obj

# target to build an object file
src/rpi-gpio.c.obj:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-gpio.c.obj
.PHONY : src/rpi-gpio.c.obj

src/rpi-gpio.i: src/rpi-gpio.c.i

.PHONY : src/rpi-gpio.i

# target to preprocess a source file
src/rpi-gpio.c.i:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-gpio.c.i
.PHONY : src/rpi-gpio.c.i

src/rpi-gpio.s: src/rpi-gpio.c.s

.PHONY : src/rpi-gpio.s

# target to generate assembly for a file
src/rpi-gpio.c.s:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-gpio.c.s
.PHONY : src/rpi-gpio.c.s

src/rpi-interrupts.obj: src/rpi-interrupts.c.obj

.PHONY : src/rpi-interrupts.obj

# target to build an object file
src/rpi-interrupts.c.obj:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-interrupts.c.obj
.PHONY : src/rpi-interrupts.c.obj

src/rpi-interrupts.i: src/rpi-interrupts.c.i

.PHONY : src/rpi-interrupts.i

# target to preprocess a source file
src/rpi-interrupts.c.i:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-interrupts.c.i
.PHONY : src/rpi-interrupts.c.i

src/rpi-interrupts.s: src/rpi-interrupts.c.s

.PHONY : src/rpi-interrupts.s

# target to generate assembly for a file
src/rpi-interrupts.c.s:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-interrupts.c.s
.PHONY : src/rpi-interrupts.c.s

src/rpi-led.obj: src/rpi-led.c.obj

.PHONY : src/rpi-led.obj

# target to build an object file
src/rpi-led.c.obj:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-led.c.obj
.PHONY : src/rpi-led.c.obj

src/rpi-led.i: src/rpi-led.c.i

.PHONY : src/rpi-led.i

# target to preprocess a source file
src/rpi-led.c.i:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-led.c.i
.PHONY : src/rpi-led.c.i

src/rpi-led.s: src/rpi-led.c.s

.PHONY : src/rpi-led.s

# target to generate assembly for a file
src/rpi-led.c.s:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-led.c.s
.PHONY : src/rpi-led.c.s

src/rpi-mailbox-interface.obj: src/rpi-mailbox-interface.c.obj

.PHONY : src/rpi-mailbox-interface.obj

# target to build an object file
src/rpi-mailbox-interface.c.obj:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-mailbox-interface.c.obj
.PHONY : src/rpi-mailbox-interface.c.obj

src/rpi-mailbox-interface.i: src/rpi-mailbox-interface.c.i

.PHONY : src/rpi-mailbox-interface.i

# target to preprocess a source file
src/rpi-mailbox-interface.c.i:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-mailbox-interface.c.i
.PHONY : src/rpi-mailbox-interface.c.i

src/rpi-mailbox-interface.s: src/rpi-mailbox-interface.c.s

.PHONY : src/rpi-mailbox-interface.s

# target to generate assembly for a file
src/rpi-mailbox-interface.c.s:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-mailbox-interface.c.s
.PHONY : src/rpi-mailbox-interface.c.s

src/rpi-mailbox.obj: src/rpi-mailbox.c.obj

.PHONY : src/rpi-mailbox.obj

# target to build an object file
src/rpi-mailbox.c.obj:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-mailbox.c.obj
.PHONY : src/rpi-mailbox.c.obj

src/rpi-mailbox.i: src/rpi-mailbox.c.i

.PHONY : src/rpi-mailbox.i

# target to preprocess a source file
src/rpi-mailbox.c.i:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-mailbox.c.i
.PHONY : src/rpi-mailbox.c.i

src/rpi-mailbox.s: src/rpi-mailbox.c.s

.PHONY : src/rpi-mailbox.s

# target to generate assembly for a file
src/rpi-mailbox.c.s:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-mailbox.c.s
.PHONY : src/rpi-mailbox.c.s

src/rpi-mutex.obj: src/rpi-mutex.c.obj

.PHONY : src/rpi-mutex.obj

# target to build an object file
src/rpi-mutex.c.obj:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-mutex.c.obj
.PHONY : src/rpi-mutex.c.obj

src/rpi-mutex.i: src/rpi-mutex.c.i

.PHONY : src/rpi-mutex.i

# target to preprocess a source file
src/rpi-mutex.c.i:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-mutex.c.i
.PHONY : src/rpi-mutex.c.i

src/rpi-mutex.s: src/rpi-mutex.c.s

.PHONY : src/rpi-mutex.s

# target to generate assembly for a file
src/rpi-mutex.c.s:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-mutex.c.s
.PHONY : src/rpi-mutex.c.s

src/rpi-systimer.obj: src/rpi-systimer.c.obj

.PHONY : src/rpi-systimer.obj

# target to build an object file
src/rpi-systimer.c.obj:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-systimer.c.obj
.PHONY : src/rpi-systimer.c.obj

src/rpi-systimer.i: src/rpi-systimer.c.i

.PHONY : src/rpi-systimer.i

# target to preprocess a source file
src/rpi-systimer.c.i:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-systimer.c.i
.PHONY : src/rpi-systimer.c.i

src/rpi-systimer.s: src/rpi-systimer.c.s

.PHONY : src/rpi-systimer.s

# target to generate assembly for a file
src/rpi-systimer.c.s:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-systimer.c.s
.PHONY : src/rpi-systimer.c.s

src/rpi-thread.obj: src/rpi-thread.c.obj

.PHONY : src/rpi-thread.obj

# target to build an object file
src/rpi-thread.c.obj:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-thread.c.obj
.PHONY : src/rpi-thread.c.obj

src/rpi-thread.i: src/rpi-thread.c.i

.PHONY : src/rpi-thread.i

# target to preprocess a source file
src/rpi-thread.c.i:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-thread.c.i
.PHONY : src/rpi-thread.c.i

src/rpi-thread.s: src/rpi-thread.c.s

.PHONY : src/rpi-thread.s

# target to generate assembly for a file
src/rpi-thread.c.s:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-thread.c.s
.PHONY : src/rpi-thread.c.s

src/rpi-trace.obj: src/rpi-trace.c.obj

.PHONY : src/rpi-trace.obj

# target to build an object file
src/rpi-trace.c.obj:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-trace.c.obj
.PHONY : src/rpi-trace.c.obj

src/rpi-trace.i: src/rpi-trace.c.i

.PHONY : src/rpi-trace.i

# target to preprocess a source file
src/rpi-trace.c.i:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-trace.c.i
.PHONY : src/rpi-trace.c.i

src/rpi-trace.s: src/rpi-trace.c.s

.PHONY : src/rpi-trace.s

# target to generate assembly for a file
src/rpi-trace.c.s:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-trace.c.s
.PHONY : src/rpi-trace.c.s

src/rpi-uart.obj: src/rpi-uart.c.obj

.PHONY : src/rpi-uart.obj

# target to build an object file
src/rpi-uart.c.obj:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-uart.c.obj
.PHONY : src/rpi-uart.c.obj

src/rpi-uart.i: src/rpi-uart.c.i

.PHONY : src/rpi-uart.i

# target to preprocess a source file
src/rpi-uart.c.i:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-uart.c.i
.PHONY : src/rpi-uart.c.i

src/rpi-uart.s: src/rpi-uart.c.s

.PHONY : src/rpi-uart.s

# target to generate assembly for a file
src/rpi-uart.c.s:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/rpi-uart.c.s
.PHONY : src/rpi-uart.c.s

src/start.obj: src/start.c.obj

.PHONY : src/start.obj

# target to build an object file
src/start.c.obj:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/start.c.obj
.PHONY : src/start.c.obj

src/start.i: src/start.c.i

.PHONY : src/start.i

# target to preprocess a source file
src/start.c.i:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/start.c.i
.PHONY : src/start.c.i

src/start.s: src/start.c.s

.PHONY : src/start.s

# target to generate assembly for a file
src/start.c.s:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/start.c.s
.PHONY : src/start.c.s

src/start.obj: src/start.s.obj

.PHONY : src/start.obj

# target to build an object file
src/start.s.obj:
	$(MAKE) -f CMakeFiles\rpi-os.dir\build.make CMakeFiles/rpi-os.dir/src/start.s.obj
.PHONY : src/start.s.obj

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... rpi-os
	@echo ... src/asm-functions.obj
	@echo ... src/cstubs.obj
	@echo ... src/cstubs.i
	@echo ... src/cstubs.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/rpi-armtimer.obj
	@echo ... src/rpi-armtimer.i
	@echo ... src/rpi-armtimer.s
	@echo ... src/rpi-assert.obj
	@echo ... src/rpi-assert.i
	@echo ... src/rpi-assert.s
	@echo ... src/rpi-event.obj
	@echo ... src/rpi-event.i
	@echo ... src/rpi-event.s
	@echo ... src/rpi-gpio.obj
	@echo ... src/rpi-gpio.i
	@echo ... src/rpi-gpio.s
	@echo ... src/rpi-interrupts.obj
	@echo ... src/rpi-interrupts.i
	@echo ... src/rpi-interrupts.s
	@echo ... src/rpi-led.obj
	@echo ... src/rpi-led.i
	@echo ... src/rpi-led.s
	@echo ... src/rpi-mailbox-interface.obj
	@echo ... src/rpi-mailbox-interface.i
	@echo ... src/rpi-mailbox-interface.s
	@echo ... src/rpi-mailbox.obj
	@echo ... src/rpi-mailbox.i
	@echo ... src/rpi-mailbox.s
	@echo ... src/rpi-mutex.obj
	@echo ... src/rpi-mutex.i
	@echo ... src/rpi-mutex.s
	@echo ... src/rpi-systimer.obj
	@echo ... src/rpi-systimer.i
	@echo ... src/rpi-systimer.s
	@echo ... src/rpi-thread.obj
	@echo ... src/rpi-thread.i
	@echo ... src/rpi-thread.s
	@echo ... src/rpi-trace.obj
	@echo ... src/rpi-trace.i
	@echo ... src/rpi-trace.s
	@echo ... src/rpi-uart.obj
	@echo ... src/rpi-uart.i
	@echo ... src/rpi-uart.s
	@echo ... src/start.obj
	@echo ... src/start.i
	@echo ... src/start.s
	@echo ... src/start.obj
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

